# Generated by Django 6.0.6 on 2026-07-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quantity1',
        ),
    ]
