# Generated by Django 6.0.6 on 2026-07-05 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('victoria', '0002_rename_quantity_product_quantity1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity1',
            new_name='quantity',
        ),
    ]
